' Gambas module file

PUBLIC FUNCTION Control(LedName AS DrawingArea, status AS String)

  draw.Begin(LedName)
  draw.FillStyle = Fill.Solid
  draw.LineWidth = 1

  IF status = "on" THEN 
    draw.FillColor = color.Green
  ELSE IF status = "off" THEN 
    draw.FillColor = color.LightGray
  ELSE IF status = "error" THEN 
    draw.FillColor = color.Red
  ELSE IF status = "busy"
    draw.FillColor = color.Orange
  ENDIF 
  draw.ForeColor = color.DarkGray
  draw.circle(10, 10, 10)
  draw.End
END

