' Gambas module file

PUBLIC FUNCTION Display(Bar AS DrawingArea, progr AS Integer)
  
  'void
  DIM procents AS Integer
  DIM kader AS Integer
  DIM i AS Integer
  IF progr > 100 THEN progr = 100   ' max limit
  kader = 6
  procents = (Bar.Width - kader) * progr / 100
  'procents = 50
  draw.Begin(Bar)
  draw.FillStyle = Fill.Solid
  draw.LineWidth = kader
  draw.ForeColor = color.White
  draw.rect(0, 0, Bar.Width, Bar.Height + 1)

    'draw.FillStyle = Fill.Dense50
    draw.ForeColor = color.Red
    draw.LineWidth = Bar.Height - kader
    draw.Line(kader / 2, Bar.Height / 2, (kader / 2 + procents), Bar.Height / 2)
  
    draw.ForeColor = color.White
    draw.LineWidth = 1
    FOR i = 1 TO 9 STEP 1
      draw.Line(kader / 2 + (i * (Bar.Width - kader) / 10), 0, kader / 2 + (i * (Bar.Width - kader) / 10), Bar.Height)
    NEXT 
  draw.End
  
END

