' Gambas module file

PUBLIC SUB Go() AS String
  DIM reply AS String
  DIM Errors AS Integer
  PRINT "Synchronization started.."
  Errors = Light_Tower()

  IF (MainAZC.StopProcess = 1) THEN 
    Errors = 2
    PRINT "Sync aborted by stop button"
    RETURN Errors
  ENDIF 
 
  Errors = Controls_To_Default()
  
  IF (MainAZC.StopProcess = 1) THEN 
    Errors = 2
    PRINT "Sync aborted by stop button"
    RETURN Errors
  ENDIF 
  RETURN Errors
END


PUBLIC SUB Controls_To_Default() AS Integer
  DIM reply AS String
  DIM Errors AS Integer = 0
  reply = SerialHandler.TxRxFast(off.output_store_move)
  reply = SerialHandler.TxRxFast(off.bowl_low_speed)
  reply = SerialHandler.TxRxFast(off.freq_1)
  reply = SerialHandler.TxRxFast(off.freq_2)
  reply = SerialHandler.TxRxFast(off.high_pressure)
  reply = SerialHandler.TxRxFast(off.water_valve_clean)
  reply = SerialHandler.TxRxFast(off.water_valve_fill)
  reply = SerialHandler.TxRxFast(off.water_valve_HP)
  reply = SerialHandler.TxRxFast(off.water_valve_tube)
  reply = SerialHandler.TxRxFast(off.pump_tube)
  reply = SerialHandler.TxRxFast(off.kaoline_valve)
  reply = SerialHandler.TxRxFast(off.magnesium_valve)
  reply = SerialHandler.TxRxFast(off.sample_valve)

  reply = SerialHandler.TxRxFast(off.input_store_rotate)  'china
  reply = SerialHandler.TxRxFast(off.pump_magnesium)      'china

  'use serial control FOR stirrer: 'china
  Stirrer.SetRpm(0)    '
  'reply = SerialHandler.TxRxFast(off.stirrer)
  'reply = SerialHandler.TxRxFast(off.stirrer_max)

  reply = SerialHandler.TxRxFast(off.output_store_rotate)
  reply = SerialHandler.TxRxFast(off.drain_bowl)          'china: drain under bowl.
'  reply = SerialHandler.TxRxFast(off.input_store_rotate)
  IF Check.Stirrer_Rotate() = "stir" THEN 
    IF Check.Stirrer_Lift() = "down" THEN 
      SerialHandler.TxRxFast(on.stirrer_lift) ' lift up
      DO
        WAIT 0.1
      LOOP UNTIL Check.Stirrer_Lift() = "up"
    ENDIF 
    SerialHandler.TxRxFast(off.stirrer_rotate)
    DO
      WAIT 0.1
    LOOP UNTIL Check.Stirrer_Rotate() = "clean"
  ENDIF
  IF Check.Stirrer_Lift() = "up" THEN 
    SerialHandler.TxRxFast(off.stirrer_lift) ' lift down
    DO
      WAIT 0.1
    LOOP UNTIL Check.Stirrer_Lift() = "down"
  ENDIF 
  RETURN Errors
END


PUBLIC SUB Light_Tower() AS Integer
  DIM reply AS String
  DIM Errors AS Integer
  reply = SerialHandler.TxRxFast(on.lamp_green)
  PRINT "green on"
  WAIT 0.1
  reply = reply & SerialHandler.TxRxFast(on.lamp_orange)
  PRINT "orange on"
  WAIT 0.1
  reply = reply & SerialHandler.TxRxFast(on.lamp_red)
  PRINT "red on"
  WAIT 0.1
  IF (reply = "ERR00ERR00ERR00") THEN 
    Errors = 0
  ELSE 
    Errors = 1
  ENDIF 
  RETURN Errors
END
