' Gambas module file

Public Sub Drain_Bowl_Position() As String 
  Dim Forward As Integer
  Dim Backward As Integer
  Dim Status As Integer
  Dim Reply As String
  Forward = PlcInputs.Read("BowlDrainForward")
  Backward = PlcInputs.Read("BowlDrainBackward")
  Status = (Forward * 2) + Backward
  If (Status = 0)
    Reply = "moving"
  Else If (Status = 1)
    Reply = "off"
  Else If (Status = 2)
    Reply = "on"
  Else
    Reply = "ERR"
  Endif
  Return Reply
End

Public Sub Output_Store_Rotate() As String
  Dim Forward As Integer
  Dim Backward As Integer
  Dim Status As Integer
  Dim Reply As String
  Forward = PlcInputs.Read("OutputRotateOn")
  Backward = PlcInputs.Read("OutputRotateOff")
  Status = (Forward * 2) + Backward
  If (Status = 0)
    Reply = "moving"
  Else If (Status = 1)
    Reply = "off"
  Else If (Status = 2)
    Reply = "on"
  Else
    Reply = "ERR"
  Endif
  Return Reply
End

Public Sub Output_Store_Move() As String
  Dim Forward As Integer
  Dim Backward As Integer
  Dim Status As Integer
  Dim Reply As String
  Forward = PlcInputs.Read("OutputMoveForward")
  Backward = PlcInputs.Read("OutputMoveBackward")
  Status = (Forward * 2) + Backward
  If (Status = 0)
    Reply = "moving"
  Else If (Status = 1)
    Reply = "off"
  Else If (Status = 2)
    Reply = "on"
  Else
    Reply = "ERR"
  Endif
  Return Reply
End

Public Sub Output_Container() As String
  Dim Status As Integer
  Dim Reply As String
  Status = PlcInputs.Read("OutputContainerPresent")
  If (Status = 1)
    Reply = "present"
  Else If (Status = 0)
    Reply = "missing"
  Else
    Reply = "ERR"
  Endif
  Return Reply
End


Public Sub Stirrer_Rotate() As String
  Dim Forward As Integer
  Dim Backward As Integer
  Dim Status As Integer
  Dim Reply As String
  Forward = PlcInputs.Read("StirrerLiftRotateForward")
  Backward = PlcInputs.Read("StirrerLiftRotateBackward")
  Status = (Forward * 2) + Backward
  If (Status = 0)
    Reply = "moving"
  Else If (Status = 1)
    Reply = "clean"
  Else If (Status = 2)
    Reply = "stir"
  Else
    Reply = "ERR"
  Endif
  Return Reply
End

Public Sub Stirrer_Lift() As String
  Dim Forward As Integer
  Dim Backward As Integer
  Dim Status As Integer
  Dim Reply As String
  Forward = PlcInputs.Read("StirrerLiftUp")
  Backward = PlcInputs.Read("StirrerLiftDown")
  Status = (Forward * 2) + Backward
  If (Status = 0)
    Reply = "moving"
  Else If (Status = 1)
    Reply = "down"
  Else If (Status = 2)
    Reply = "up"
  Else
    Reply = "ERR"
  Endif
  Return Reply
End

Public Sub Input_Container_Fill() As String
  Dim Status As Integer
  Dim Reply As String
  reply = "ERR"
  While PlcInputs.Read("InputCoverClosed") = "0"
    If MainAZC.StopProcess = 1 Then Goto finish
    Message.Title = "Attention"
    Message.Warning("Please close Input Cover")
    Wait 1
  Wend
  Status = PlcInputs.Read("InputContainerPresent")
  If (Status = 1)
    Reply = "present"
  Else If (Status = 0)
    Reply = "missing"
  Else
    Reply = "ERR"
  Endif
finish:
  Return Reply
End



Public Sub Input_Store_Position() As String
  Dim Status As Integer
  Dim Reply As String
  Status = PlcInputs.Read("InputPosition")
  If (Status = 1)
    Reply = "on"
  Else If (Status = 0)
    Reply = "off"
  Else
    Reply = "ERR"
  Endif
  Return Reply
End

'TODO
Public Sub Input_Store_Rotate_Done() As String 'input store rotate action completed?
  Dim Reply As String
  Reply = Input_Store_Position()
  
  'Dim rotate As Integer
  'Reply = SerialHandler.TxRxFast("rotatedone?")
  'rotate = Val(Reply)
  If (Reply = "on") Then
    Reply = "done"
  Else If (Reply = "off") Then
    Reply = "busy"
  'Else If (rotate = -1) Then
  '    Reply = "timeout"
  Else
      Reply = "err"
  Endif
  Return Reply
End



Public Sub Fill_Status() As String 
  Dim Reply As String
  Dim ReceivedData As String
  ReceivedData = SerialCpuComm.TxRxFast("waterfillstatus?", 1)
  'Print ReceivedData 'debugger
  If Comp(ReceivedData, "Stop") = 0 Then
    Reply = "stopped"
  Else If Comp(ReceivedData, "Start") = 0 Then
    Reply = "busy"
  Else If Comp(ReceivedData, "Pending") = 0 Then
    Reply = "busy"
  Else If Comp(ReceivedData, "Done") = 0 Then
    Reply = "done"
  Else If Comp(ReceivedData, "Timeout") = 0 Then
    Reply = "timeout"
  Else
      Reply = "err"
  Endif
  Return Reply
End


Public Sub Water_Level() As String
  Dim Status As Integer
  Dim Reply As String
  Status = PlcInputs.Read("InputContainerLevel")
  If (Status = 1)
    Reply = "true"
  Else If (Status = 0)
    Reply = "false"
  Else
    Reply = "ERR"
  Endif
  Return Reply
End


Public Sub Kaoline_Level() As String
  Dim Status As Integer
  Dim Reply As String
  Status = PlcInputs.Read("KaolineLevel")
  If (Status = 1)
    Reply = "true"
  Else If (Status = 0)
    Reply = "false"
  Else
    Reply = "ERR"
  Endif
  Return Reply
End


Public Sub Magnesium_Level() As String
  Dim Status As Integer
  Dim Reply As String
  Status = PlcInputs.Read("MagnesiumLevel")
  If (Status = 1)
    Reply = "true"
  Else If (Status = 0)
    Reply = "false"
  Else
    Reply = "ERR"
  Endif
  Return Reply
End


Public Sub TubeValve_Sample() As String
  Dim Status As Integer
  Dim Reply As String
  Status = PlcInputs.Read("TubeValveSample")
  If (Status = 0)
    Reply = "off"
  Else If (Status = 1)
    Reply = "on"
  Else
    Reply = "ERR"
  Endif
  Return Reply
End


Public Sub TubeValve_Magnesium() As String
  Dim Status As Integer
  Dim Reply As String
  Status = PlcInputs.Read("TubeValveMagnesium")
  If (Status = 0)
    Reply = "off"
  Else If (Status = 1)
    Reply = "on"
  Else
    Reply = "ERR"
  Endif
  Return Reply
End

Public Sub TubeValve_Kaoline() As String
  Dim Status As Integer
  Dim Reply As String
  Status = PlcInputs.Read("TubeValveKaoline")
  If (Status = 0)
    Reply = "off"
  Else If (Status = 1)
    Reply = "on"
  Else
    Reply = "ERR"
  Endif
  Return Reply
End

Public Sub Kaoline_Motor() As String
  Dim Status As Integer
  Dim Reply As String
  Status = PlcInputs.Read("KaolineConnected")
  If (Status = 1)
    Reply = "true"
  Else If (Status = 0)
    Reply = "false"
  Else
    Reply = "ERR"
  Endif
  Return Reply
End
