' Gambas module file

Public Sub Stop()
  Print "stop triggered"
  SerialCpuComm.TxRxFast("red", 1)
  Print "red on, others off"
 
  PlcOutputs.Set("InputMotor", 0)
  PlcOutputs.Set("HpPumpPower", 0)
  PlcOutputs.Set("WaterValveStirrerClean", 0)
  SerialCpuComm.TxRxFast("waterfillstop", 1)
  PlcOutputs.Set("WaterValveHpPump", 0)
  PlcOutputs.Set("WaterValveTubes", 0)
  PlcOutputs.Set("AirTubeValveKaoline", 0)
  Do
	   Wait 0.1
  Loop Until Check.TubeValve_Kaoline() = "off"
  PlcOutputs.Set("AirTubeValveMagnesium", 0)
  Do
	   Wait 0.1
  Loop Until Check.TubeValve_Magnesium() = "off"
  PlcOutputs.Set("AirTubeValveSample", 0)
  Do
	   Wait 0.1
  Loop Until Check.TubeValve_Sample() = "off"
  PlcOutputs.TubePump("off")

  FreqCtrl.SetFreq(0.0, "OFF")
  ' TODO: read freq controller via RS485 for actual status

  'use new serial control for Stirrer:
  Stirrer.SetRpm(0)    '

  Print "end stop"
End
