' Gambas module file

Public Sub Stop()
  Print "stop triggered"
  SerialCpuComm.TxRxFast("red", 1)
  Print "red on, others off"
 
  PlcOutputs.Set("InputMotor", 0)
  PlcOutputs.Set("HpPumpPower", 0)
  PlcOutputs.Set("WaterValveStirrerClean", 0)
  SerialCpuComm.TxRxFast("waterfillstop", 1)
  PlcOutputs.Set("WaterValveHpPump", 0)
  PlcOutputs.Set("WaterValveTubes", 0)
  PlcOutputs.Set("AirTubeValveKaoline", 0)
  PlcOutputs.Set("AirTubeValveMagnesium", 0)
  PlcOutputs.Set("AirTubeValveSample", 0)
  PlcOutputs.Set("TubePumpPower", 0)

  FreqCtrl.SetFreq(0.0, "OFF")
  ' TODO: read freq controller via RS485 for actual status

  'use new serial control for Stirrer:
  Stirrer.SetRpm(0)    '

  Print "end stop"
End
