' Gambas module file

Public Sub Stop()
  Print "stop triggered"
  ' TODO: lamps
  'SerialHandler.TxRx({On}.lamp_red)
  'SerialHandler.TxRx(off.lamp_green)
  'SerialHandler.TxRx(off.lamp_orange)
  Print "red on, others off"
 
  PlcOutputs.Set("InputMotor", 0)
  PlcOutputs.Set("HpPumpPower", 0)
  PlcOutputs.Set("WaterValveStirrerClean", 0)
  SerialCpuComm.TxRxFast("waterfillstop")
  PlcOutputs.Set("WaterValveHpPump", 0)
  PlcOutputs.Set("WaterValveTubes", 0)
  PlcOutputs.Set("AirTubeValveKaoline", 0)
  PlcOutputs.Set("AirTubeValveMagnesium", 0)
  PlcOutputs.Set("AirTubeValveSample", 0)
  PlcOutputs.Set("TubePumpPower", 0)

  ' TODO: freq control via RS485 !!!!

  'use new serial control for stirrer
  Stirrer.SetRpm(0)    '

  Print "end stop"
End
