' Gambas module file

Public Sub Go() As String
  Dim Errors As Integer
  Print "Synchronization started.."
  Errors = Light_Tower()

  If (MainAZC.StopProcess = 1) Then
    Errors = 2
    Print "Sync aborted by stop button"
    Return Errors
  Endif
 
  Errors = Controls_To_Default()
  
  If (MainAZC.StopProcess = 1) Then
    Errors = 2
    Print "Sync aborted by stop button"
    Return Errors
  Endif
  Return Errors
End


Public Sub Controls_To_Default() As Integer
  Dim Errors As Integer = 0
  
  SerialCpuComm.TxRxFast("waterfillstop", 1)

  PlcOutputs.OutputStoreMove("rest")
  ' TODO: freq control via RS485
  PlcOutputs.Set("HpPumpPower", 0)
  PlcOutputs.Set("TubePumpPower", 0)
  PlcOutputs.Set("AirTubeValveMagnesium", 0)
  PlcOutputs.Set("WaterValveStirrerClean", 0)
  PlcOutputs.Set("WaterValveHpPump", 0)
  PlcOutputs.Set("WaterValveTubes", 0)
  
  PlcOutputs.Set("InputMotor", 0)
  PlcOutputs.Set("AirTubeValveKaoline", 0)
  PlcOutputs.Set("TubePumpPower", 0)
  PlcOutputs.Set("AirTubeValveSample", 0)

  PlcOutputs.OutputStoreRotate("off")
  PlcOutputs.BowlDrain("underbowl")
  
  'use serial control FOR stirrer:
  Stirrer.SetRpm(0)    '
  StirProcess.MoveStir("clean")
  
  Return Errors
End


Public Sub Light_Tower() As Integer
  Dim reply As String
  Dim Errors As Integer
  ' TODO: lamps
'  reply = SerialHandler.TxRxFast({On}.lamp_green)
  Print "green on"
  Wait 0.1
'  reply = reply & SerialHandler.TxRxFast({On}.lamp_orange)
  Print "orange on"
  Wait 0.1
'reply = reply & SerialHandler.TxRxFast({On}.lamp_red)
  Print "red on"
  Wait 0.1
  If (reply = "ERR00ERR00ERR00") Then
    Errors = 0
  Else
    Errors = 1
  Endif
  Return Errors
End
