' Gambas module file

Public Sub Go() As String
  Dim Errors As Integer
  Print "Synchronization started.."
  Errors = Light_Tower()

  If (MainAZC.StopProcess = 1) Then
    Errors = 2
    Print "Sync aborted by stop button"
    Return Errors
  Endif
 
  Errors = Controls_To_Default()
  
  If (MainAZC.StopProcess = 1) Then
    Errors = 2
    Print "Sync aborted by stop button"
    Return Errors
  Endif
  Return Errors
End


Public Sub Controls_To_Default() As Integer
  Dim Errors As Integer = 0
  
  SerialCpuComm.TxRxFast("waterfillstop", 1)

  PlcOutputs.OutputStoreMove("rest")
  FreqCtrl.SetFreq(0.0, "OFF")
  ' TODO: read freq controller via RS485 for actual status
  PlcOutputs.Set("HpPumpPower", 0)
  PlcOutputs.Set("TubePumpPower", 0)
  PlcOutputs.Set("AirTubeValveMagnesium", 0)
  PlcOutputs.Set("WaterValveStirrerClean", 0)
  PlcOutputs.Set("WaterValveHpPump", 0)
  PlcOutputs.Set("WaterValveTubes", 0)
  
  PlcOutputs.Set("InputMotor", 0)
  PlcOutputs.Set("AirTubeValveKaoline", 0)
  PlcOutputs.Set("TubePumpPower", 0)
  PlcOutputs.Set("AirTubeValveSample", 0)

  PlcOutputs.OutputStoreRotate("off")
  PlcOutputs.BowlDrain("underbowl")
  
  'use serial control FOR Stirrer:
  Stirrer.SetRpm(0)    '
  StirProcess.MoveStir("clean")
  
  Return Errors
End


Public Sub Light_Tower() As Integer
  SerialCpuComm.TxRxFast("green", 1)
  Wait 0.1
  SerialCpuComm.TxRxFast("blue", 1)
  Wait 0.1
  SerialCpuComm.TxRxFast("red", 1)
  Wait 0.1
  Return 0
End
