' Gambas module file

Public Stir_Time As Integer

Public Magnesium_Fill_Time As Integer
Public Kaoline_Fill_Time As Integer
Public Sample_Time As Integer
Public Bowl_Stop_Delay As Integer
Public Bowl_Speedup_Time As Integer
Public Bowl_Water_Fill_Time As Integer
Public Kaoline_Valve_Clean_Time As Integer
Public Centrifuge_Time As Integer
Public Output_Capture_Time As Integer
Public Bowl_Clean_Time As Integer

Public Stirrer_Clean_Time As Integer
Public Tube_Clean As Integer
Public Bowl_Clean_Phase1_Time As Integer
Public Bowl_Clean_Phase2_Time As Integer
Public Bowl_Clean_Phase3_Time As Integer
Public Motor_ACC As Integer
Public Motor_DEC As Integer



